<?php
if(session_status()===PHP_SESSION_NONE) {
    session_start();
}elseif(isset($_SESSION["role"]) && isset($_SESSION["username"])) {
    $role = $_SESSION["role"];
    $username = $_SESSION["username"];
}
$db=new Database();
$result=$db->query_execute("select * from user");
?>
<html>
<head>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/material-design-lite/1.1.0/material.min.css" type="text/css">
    <link href="https://cdn.datatables.net/1.10.15/css/dataTables.material.min.css" type="text/css">

    <!--Datatables -->
    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.15/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.15/js/jquery.dataTables.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/dataTables.material.min.js"></script>

    <script src="http://localhost/Vaulty/Public/js/dataTB.js"></script>

    <link href="http://localhost/Vaulty/Public/css/gradient.css" />
    <script src="http://localhost/Vaulty/Public/js/gradient.js"></script>
</head>
<body>
<div id="gradient" >
    <div class="container">

    </div>
</div>
</body>
</html>

