<?php
if(!isset($_SESSION['username'])){
    Redirect::redirectUrl('/home');
}else{
    $username=$_SESSION['username'];
}
$result=Database::query_execute("select * from asset where public='1'");
?>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!-- Material design-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/material-design-lite/1.1.0/material.min.css" type="text/css">
    <link href="https://cdn.datatables.net/1.10.15/css/dataTables.material.min.css" type="text/css">

    <!--Datatables -->
    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.15/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.15/js/jquery.dataTables.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/dataTables.material.min.js"></script>
    <script src="/Public/js/dataTB.js"></script>

    <!-- Custom CSS -->
    <link href="/Public/css/input.css">

<script data-require="datatables@*" data-semver="1.10.12" src="//cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.13/js/dataTables.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.1.0/js/dataTables.responsive.js"></script>

<link href="//cdn.datatables.net/responsive/2.1.1/css/dataTables.responsive.css"/>
<link data-require="datatables@*" data-semver="1.10.12" rel="stylesheet" href="//cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css" />
</head>
<style>
.container{

}
</style>
<body>
<!--<div id="gradient">-->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-brand-centered">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="navbar-brand navbar-brand-centered"><?php echo "Hello, ".$username;?></div>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="navbar-brand-centered">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="/upload">Upload</a></li>
                    <li><a href="/download">Download</a></li>
                    <li><a href="/logout">Logout</a></li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    <div class="container">
    <div class="row">
        <div class="iconmelon">
            <svg viewBox="-70 0 185 32">
                <g filter="">
                    <use xlink:href="#git"></use>
                </g>
            </svg>
        </div>
    </div>

    <?php
    echo '<table id="files" class="display nowrap">';
        echo '<thead>';
        echo '<tr>';
            echo '<th>File Title</th>
            <th data-priority="1">Name</th>
            <th>Type</th>
            <th>Size</th>
            <th>Description</th>
            <th>User</th>
            <th data-priority="3" >Downloads</th>
            <th data-priority="2" >Download Link</th>';
            echo '</tr>';
        echo '</thead>';
        echo '<tbody>';
        foreach ($result as $item){
        echo '<tr>';
            echo '<td>'.$item['title'].'</td>
            <td>'.$item['reference'].'</td>
            <td>'.$item['mime_type'].'</td>
            <td>'.$item['size'].'</td>
            <td>'.$item['description'].'</td>
            <td>'.$item['user'].'</td>
            <td>'.$item['downloaded'].'</td>
            <td><a href="/download/submit/?file='.$item['reference'].'">Download</a></td>';
            echo '</tr>';
        }
        echo '</tbody>';
        echo '</table>';
?>
</div>
</body>
</html>