<!DOCTYPE html>
<html>
<head>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!-- Material design-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/material-design-lite/1.1.0/material.min.css" type="text/css">
    <link href="https://cdn.datatables.net/1.10.15/css/dataTables.material.min.css" type="text/css">

     <meta name="viewport" content="width=device-width, initial-scale=1">


</head>

<body>

<style>
    .input-group-addon{
        width: 40% !important;
        text-align:left !important;
    }
    .input-group {
        width: 100%;
        padding-bottom: 5px;
    }

    .alert-danger{
    position: absolute !important;
        left: 10px !important;
        top: 10px !important;
    }

    #warningLogin1{
        margin-top: 9em !important;
    }

</style>

<div class="container">
    <div id="loginbox" class="mainbox col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3">

        <div class="row">
            <div class="iconmelon">
                <svg viewBox="-7 0 50 35">
                    <g filter="">
                        <use xlink:href="#git"></use>
                    </g>
                </svg>
            </div>
        </div>

        <div class="panel panel-default" >
            <div class="panel-heading">
                <div class="panel-title text-center">Sign In!</div>
            </div>

            <div class="panel-body" >
                <form name="logform" id="logform" class="form-horizontal" enctype="multipart/form-data" method="">

                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i>Username</span>
                        <input id="user" type="text" class="form-control" name="username" value="" placeholder="User" required>
                    </div>

                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i>Password</span>
                        <input id="password" type="password" class="form-control" name="password" placeholder="Password" required>
                    </div>

                    <div class="form-group">
                        <!-- Button -->
                        <div class="col-sm-12 controls">
                            <button type="submit"  name="button" class="btn btn-primary pull-right button"><i class="glyphicon glyphicon-log-in"></i> Log in</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>

    <div id="registerbox" class="mainbox col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3">
    <div class="panel panel-default" >
        <div class="panel-heading">
            <div class="panel-title text-center">Sign Up!</div>
        </div>

        <div class="panel-body" >

            <form name="form" id="form" class="form-horizontal" enctype="multipart/form-data" method="POST" action='/home/register'>

                <div class="input-group">
                    <span id="usernameL" class="input-group-addon"><i class="glyphicon glyphicon-user"></i>Username</span>
                    <input id="usernameR" type="text" class="form-control" name="usernameR" value="" placeholder="User" required>
                </div>

                <div class="input-group">
                    <span id="emailL" class="input-group-addon"><i class="glyphicon glyphicon-user"></i>Email</span>
                    <input id="emailR" type="text" class="form-control" name="emailR" placeholder="Email" required>
                </div>

                <div class="input-group">
                    <span id="passwordL" class="input-group-addon"><i class="glyphicon glyphicon-lock"></i>Password</span>
                    <input id="passwordR" type="password" class="form-control" name="passwordR" placeholder="Password" required>
                </div>

                <div class="input-group">
                    <span id="passwordRL" class="input-group-addon"><i class="glyphicon glyphicon-lock"></i>Repeat password</span>
                    <input id="passwordRP" type="password" class="form-control" name="passwordRP" placeholder="Repeat password" required>
                </div>

                <div class="form-group">
                    <!-- Button -->
                    <div class="col-sm-12 controls">
                        <button id="register" type="submit" href="#" class="btn btn-primary pull-right"><i class="glyphicon glyphicon-log-in"></i> Sign Up!</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    </div>
</div>

<div id="warningLogin" class="alert alert-danger">
    <strong> Login credentials: <br/>
             Username: user <br/>
             Password: 123456 <br/><br/>
    </strong>
</div>
<div id="warningLogin1" class="alert alert-danger" style="display:none"></div>
<script src="/Public/js/login.js"></script>
<script src="/Public/js/validation.js"></script>
</body>
</html>
