<?php

if(!isset($_SESSION['username'])){
    Redirect::redirectUrl('/home');
}else{
    $username=$_SESSION['username'];
}
?>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!-- Material design-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/material-design-lite/1.1.0/material.min.css" type="text/css">
    <link href="https://cdn.datatables.net/1.10.15/css/dataTables.material.min.css" type="text/css">

    <!--Datatables -->
    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.15/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.15/js/jquery.dataTables.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/dataTables.material.min.js"></script>
    <script src="/Public/js/dataTB.js"></script>

    <!-- Custom CSS -->
    <link href="/Public/css/input.css">
</head>
<style>
#warningLogin1{
    margin-top: -1.5em !important;
}
.form{
left: 25%;
right: 25%;
}
</style>
<body>

    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-brand-centered">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="navbar-brand navbar-brand-centered"><?php echo "Hello, ".$username;?></div>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="navbar-brand-centered">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="/upload">Upload</a></li>
                    <li><a href="/download">Download</a></li>
                    <li><a href="/logout">Logout</a></li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>

    <div id="warningLogin1" class="alert alert-danger" style="display: none"></div>
    <div id="warningLogin2" class="alert alert-success" style="display: none"></div>

    <div class="container">
        <div class="row">
            <div class="iconmelon">
                <svg viewBox="-70 0 185 32">
                    <g filter="">
                        <use xlink:href="#git"></use>
                    </g>
                </svg>
            </div>
        </div>

    <form action="/upload/submit" method="post" enctype="multipart/form-data">
        <div class="form-group">
            <label for="exampleInputEmail">File Title</label>
            <input type="text" class="form-control" id="title" name="title" aria-describedby="titleHelp" placeholder="Enter file title" required>
            <small id="titleHelp" class="form-text text-muted">This title will be displayed.</small>
        </div>

        <div class="form-group">
            <label for="exampleInputEmail">File Description</label>
            <input type="text" class="form-control" id="description" name="description" aria-describedby="descriptionHelp" placeholder="Enter file description" required>
            <small id="descriptionHelp" class="form-text text-muted">Describe your file.</small>
        </div>

        <fieldset class="form-group">
            <legend>Is this file public or private?</legend>
            <div class="form-check">
                <label class="form-check-label">
                    <input type="radio" class="form-check-input" name="optionsRadios" id="optionsRadios1" value="1" checked>
                    My file is public.
                </label>
            </div>
            <div class="form-check">
                <label class="form-check-label">
                    <input type="radio" class="form-check-input" name="optionsRadios" id="optionsRadios2" value="0">
                    My file is private.
                </label>
            </div>
        </fieldset>
        Select image to upload:
        <input type="file" name="fileToUpload" id="fileToUpload" required>
        <input type="submit" class="btn btn-primary" value="Upload File" name="submit">
    </form>

</div>
<script src="/Public/js/warning.js"></script>
</body>
</html>